services:
  frontend:
    image: node:22-alpine
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      VITE_API_URL: ${VITE_API_URL}

  backend:
    image: node:22-alpine
    ports:
      - 3000:3000
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && node index.js"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data: